routes/web.php
<?php


$this ->group(['middleware' => ['auth'], 'namespace' => 'produto'], function(){
   $this->get('produto', 'ProdutosController@index');
    
});

Auth::routes();
Route::get('/', function () {
  return view('welcome');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/produto', 'ProdutosController@index')->name('produto');
Route::get('/produto/incluir', 'ProdutosController@create')->name('incluir');
Route::get('/cliente/incluir', 'ClienteController@create')->name('cadastrar');
Route::get('/cliente/exibir', 'ClienteController@index')->name('exibir'); 
Route::resource('product','ProdutosController');
Route::resource('cliente','ClienteController');
Route::resource('pdv','PdvController'); 
Route::resource('OS','OsController');
Route::resource('registro', 'RegistroController');
Route::resource('edit-registro-item', 'EditRegistro');
$this->get('/pdv','PdvController@show')->name('show');
$this->get('/pdv-alter','PdvController@truncate')->name('truncate');
$this->post('/pdv/cliente','PdvController@searchCliente')->name('search.cliente');
Route::get('/registro', 'RegistroController@index')->name('registro');
Route::post('/registro', 'RegistroController@calcular')->name('calcular');
Route::get('/registro-option', 'RegistroController@taxa')->name('registro.taxa');
Route::post('/registro-option', 'RegistroController@destroy')->name('destroy');
Route::post('/registro-register', 'RegistroController@register')->name('register');
Route::post('/OS','OsController@save')->name('OS.save');
Route::get('/OS-show','OsController@show')->name('os.show');
Route::get('/vendas', 'RegistroController@show')->name('vendas');
Route::get('/edit-registro-item', 'RegistroController@alter')->name('alter');
Route::post('/edit-registro', 'RegistroController@remove')->name('remove');
Route::get('/imprimir', 'PdvController@imprimir')->name('imprimir');
Route::get('/imprimir-os', 'OsController@imprimir')->name('imprimir.os');

app/Pdv.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pdv extends Model
{     
    protected $fillable = ['cliente','name','description','quantity','price','priceone','imagem'];
    protected $guarded = ['id', 'created_at', 'update_at'];
    protected $table = 'pdvs'; 
}

app/Http/Controllers/PdvController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ClienteTable;
use App\Produto;
use App\User;
use App\ClienteLocal;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\QueryException;
use App\Pdv;
use App\taxa;

class PdvController extends Controller
{
    public function index(Request $request) {      
        $produtoPdv = Pdv::all();
        $total = Pdv::all()->count();
        $cpf = "";
        $product = new taxa;
        $product->taxa = "0.00";
        $product->save(); 
        $cp = $request->input('cpf');     
        if(empty($cp)){             
		$produtos = DB::table('cliente_tables')->where('cpf', $cp)->value('name');
        return view('pdv.pdv', compact ('produtos','produtoPdv','total','cpf'));    
    }  
        $produtos = DB::table('cliente_tables')->where('cpf', $cp)->value('name');
        dd($cp); 
        //return view('pdv.pdv', compact ('produtos','produtoPdv', 'total','cpf'));
}
    public function truncate(){
        $pdv = DB::table('pdvs')->truncate();
        $cliente = DB::table('cliente_locals')->truncate();
        return redirect()->route('show')->with('message', 'Produto excluído com sucesso!');
}
    
    
    public function show(Request $request) {   
        $produtoPdv = Pdv::all();
        $total = Pdv::all()->count();
        $cpf = "";
        $product = new taxa;
        $product->taxa = "0.00";
        $product->save(); 
        $cp = $request->input('cpf');     
        if(empty($cp)){ 
        $cpf = DB::table('cliente_locals')->value('cpf');
		$produtos = DB::table('cliente_tables')->where('cpf', $cpf)->value('name');
        return view('pdv.pdv', compact ('produtos','produtoPdv','total', 'cpf'));    
        }          
        $cpf = DB::table('cliente_locals')->value('cpf');       
        $produtos = DB::table('cliente_tables')->where('cpf', $cpf)->value('name');
        return view('pdv.pdv', compact ('produtos','produtoPdv','total', 'cpf'));    
}
    
    public function searchCliente(Request $request){
        $produtoPdv = Pdv::all();
        $total = Pdv::all()->count();
       
        $cpf = $request->input('cpf'); 
        $cp = $cpf;    
        
        if(empty($cpf)){
            
            
        $cpf = DB::table('cliente_locals')->value('cpf');
                             
        $cod = $request->input('CodItem'); 
        $qtd = $request->input('Qtde');  
        $name = DB::table('produtos')->where('id', $cod)->value('name');
        $desc = DB::table('produtos')->where('id', $cod)->value('description');
        $qtde = $qtd;
        $tipy = $request->input('tipy');         
        $price = DB::table('produtos')->where('id', $cod)->value($tipy);
        $priceTot = $qtd * $price;
        $imagem = DB::table('produtos')->where('id', $cod)->value('imagem');
        $cliente = DB::table('cliente_locals')->value('name');
        
        $product = new Pdv;
        $product->cliente = $cliente;
        $product->name = $name;
        $product->description = $desc;
        $product->quantity = $qtde;
        $product->price = $priceTot;
        $product->priceone = $price;
        $product->imagem = $imagem;
        try{
        $product->save();
        }catch (QueryException $e) {
            echo "Produto não encontrado! ";
            $cpf = DB::table('cliente_locals')->value('cpf');        
        $produtos = DB::table('cliente_tables')->where('cpf', $cpf)->value('name');
        return view('pdv.pdv', compact ('produtos','produtoPdv','total', 'cpf'));  
        }
        $cpf = DB::table('cliente_locals')->value('cpf');        
        $produtos = DB::table('cliente_tables')->where('cpf', $cpf)->value('name');
        return redirect()->route('show')->with('message', 'Produto criado com sucesso!');
    } 
          else{
            
        $cpf = $request->input('cpf');         
        $cod = $request->input('CodItem'); 
        $qtd = $request->input('Qtde');         
        $cliente = $request->input('clienteName');
        $name = DB::table('cliente_tables')->where('cpf', $cpf)->value('name');
        $email = DB::table('cliente_tables')->where('cpf', $cpf)->value('email');
        $celular = DB::table('cliente_tables')->where('cpf', $cpf)->value('celular');
        $cep = DB::table('cliente_tables')->where('cpf', $cpf)->value('cep');
        $rua = DB::table('cliente_tables')->where('cpf', $cpf)->value('rua');
        $bairro = DB::table('cliente_tables')->where('cpf', $cpf)->value('bairro');
        $cidade = DB::table('cliente_tables')->where('cpf', $cpf)->value('cidade');
        $product = new ClienteLocal;
        $product->name = $name;
        $product->cpf = $cpf;
        $product->email = $email;
        $product->celular = $celular;
        $product->cep = $cep;
        $product->rua = $rua;
        $product->bairro = $bairro;
        $product->cidade = $cidade;
        try{
            $product->save();
            }catch (QueryException $e) {
                echo "CPF não encontrado! " ;
                $cpf = $request->input('cpf'); 
        $produtos = $request->input('ClienteName');           
        $cpf = DB::table('cliente_locals')->value('cpf');         
        $produtos = DB::table('cliente_tables')->where('cpf', $cpf)->value('name');
        return view('pdv.pdv', compact ('produtos','produtoPdv','total', 'cpf'));  
        
            }
        $cpf = $request->input('cpf'); 
        $produtos = $request->input('ClienteName');           
        $cpf = DB::table('cliente_locals')->value('cpf');         
        $produtos = DB::table('cliente_tables')->where('cpf', $cpf)->value('name');
        return view('pdv.pdv', compact ('produtos','produtoPdv','total', 'cpf'));  
        
   
    }
 
        $cpf = DB::table('cliente_locals')->value('cpf');        
        $produtos = DB::table('cliente_tables')->where('cpf', $cpf)->value('name');
        return view('pdv.pdv', compact ('produtos','produtoPdv','total', 'cpf'));
    } 

    public function update(Request $request, $id) {
        $product = Pdv::findOrFail($id); 
        $product->name = $request->name;
        $product->description = $request->description;
        $product->quantity = $request->quantity;
        $product->price = $request->price;
        $product->save();
        return redirect()->route('show')->with('message', 'Produto alterado com sucesso!');
    }   
    public function imprimir() {
        
        
        return view('pdv.imprimir');
    }

    public function edit($id) {
        $product = Pdv::findOrFail($id);
        
        return view('pdv.edit-pdv', compact('product'));
    }


    public function save(Request $request){
        $cod = $request->input('CodItem'); 
        $qtd = $request->input('Qtde'); 
        $product = Produto::findOrFail($cod);
        $pdv = new Pdv;
        $pdv->name = $request->name;
        $pdv->description = $request->description;
        $pdv->quantity = $request->quantity;
        $pdv->price = $request->price;
        $pdv->imagem = $request->imagem;
        $pdv->save(); 
        $produtoPdv = Pdv::all();
        $total = Pdv::all()->count();
        //dd($produtoPdv);
        return view('pdv.pdv', compact ('produtos','produtoPdv','total'));
    }

    public function destroy($id) {
        $product = Pdv::findOrFail($id);
        $product->delete();
        return redirect()->route('show')->with('message', 'Produto excluído com sucesso!');
    }

    public function remove($id) {
        $product = Produto::findOrFail($id);
        $product->delete();
        return redirect()->route('vendas')->with('message', 'Produto excluído com sucesso!');
    }

}

resources/views/pdv/edit-pdv.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')
<div id="saudacao">
<?php 
  echo "Seja bem vindo(a)!";
?>
</div>
@stop

@section('content')
<!DOCTYPE html>
<html lang="en">
<body>
<div id="line-one">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="center">              
                        <h1><b>Item</b></h1>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="">Panel</a></li>                  
                            <li><a href="{{route('product.index')}}">Pdv</a></li>                  
                            <li class="active">Alteração</li>
                        </ol>              
                    </div>          
                </div>
                <div class="row">  
                    <br>
                    <h4 id="center"><b>ALTERAÇÃO DO ITEM</b></h4>
                    <br> 
                    <form method="post" 
                          action="{{route('pdv.update', $product->id)}}" 
                          enctype="multipart/form-data">
                        {!! method_field('put') !!}
                        {{ csrf_field() }}
                        <div class="col-md-6">              
                            <div class="form-group">
                                <label for="name">Nome</label>
                                <input type="text" name="name" 
                                       class="form-control" 
                                       value="{{$product->name or old('name')}}"
                                       required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="foto">Foto</label>
                                <input type="text" 
                                       accept=".gif,.jpg,.png"
                                       class="form-control"
                                       data-toggle="tooltip" 
                                       data-placement="top"
                                       title="Usar arquivo com dimensões 300x300 
                                       - JPG, GIF, PNG"
                                       value="{{$product->imagem or old('imagem')}}">
                            </div>   
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="description">Descrição</label>
                                <input type="text" name="description" 
                                       class="form-control" 
                                       value="{{$product->description or old('description')}}"
                                       required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="quantity">Quantidade</label>
                                <input type="number" name="quantity" 
                                       class="form-control" 
                                       value="{{$product->quantity or old('quantity')}}"
                                       required>
                            </div>    
                        </div>                 
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="price">Preço</label>
                                <input type="text" name="price"                               
                                       class="form-control"
                                       value="{{$product->price or old('price')}}"
                                       required>
                            </div>
                        </div>                       
                        <div class="col-md-12">                   
                            <button type="reset" class="btn btn-default">
                                Limpar
                            </button>
                            <button type="submit" 
                                    class="btn btn-warning" id="black">
                                Alterar
                            </button>
                        </div>
                    </form>             
                </div>
            </div>
        </div>
    </body>
</html>
@stop

resources/views/pdv/pdv-alter.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')

@stop

@section('content')
<!DOCTYPE html>
<html lang="en">

<body>
<div id="line-one">   
            <div class="container">
                <div class="row">
                    <div class="col-md-8" id="center"> 
                        <h1><b>PDV</b></h1>
                        <br>
                    </div>
                </div>
                <div class="box-header">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="#">Panel</a></li>                  
                            <li class="active">Pdv</li>
                        </ol>
                        <br>
                        
                            <div id="pesqClie" class="form form-inline">
                            <form class="form-group" method="post" 
                                  action="{{ route ('search.cliente')}}" > 
                                  {!!csrf_field()!!}                                  
                                  <input type="text" name="cpf" 
                                       class="form-control input-sm pull-left" 
                                       placeholder="CPF do cliente..."
                                       value="{{$cpf}}"
                                       required>
                                <button class="btn btn-default btn-sm pull-right" 
                                        id="color"> 
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                                </form> 
                                <input type="text" name="clienteName" size ="70" 
                                       class="form-control input-sm pull-center" 
                                       value="{{$produtos}}"
                                       required>  

                        <div id="pesquisaProduto" class="pull-right">
                            <form class="form-group" method="post" 
                                  action="{{ route ('search.cliente')}}">
                                  {!! csrf_field() !!}                                   
                                <input type="text" name="CodItem" 
                                       class="form-control input-sm pull-left" 
                                       placeholder="Código do item..." required> 
                                <button class="btn btn-default btn-sm pull-right" 
                                        id="color">                                         
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                                <input type="text" name="Qtde" size ="5" 
                                       class="form-control input-sm pull-center" 
                                       placeholder="Qtde..." required>                                        
                                <a href="{{route('product.create')}}" 
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Adicionar</a>
                            </form>
                        </div>                      
                    </div>  
                           
                </div>
                <div class="row">
                    <div class="col-md-12">   
                        <br /><a href="{{route('show')}}" style='background-color:#ff1919' size='35'
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Limpar</a>
                        
                        <a href="{{route('registro')}}" style='background-color: #2dad2d' size='35'
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Registrar</a>
                        <h4 id="center"><b>Registro de Itens </b></h4>
                         
                        <br>
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                    <th id="center">Código</th>
                                        <th>Nome</th>
                                        <th>Descrição</th>
                                        <th id="center">Quantidade</th>
                                        <th>Preço</th>                
                                        <th id="center">Imagem</th>                
                                        <th id="center">Ações</th>              
                                                      
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($produtoPdv as $produto)
                                    <tr>
                                        <td id="center">{{$produto->id}}</td>
                                        <td title="Nome">{{$produto->name}}</td>
                                        <td title="Descrição">{{$produto->description}}</td>
                                        <td title="Quantidade" id="center">{{$produto->quantity}}</td>
                                        <td title="Preço">R$ {{number_format($produto->price, 2,',','.')}}</td> 
                                        <td id="center">
                                            <a href="{{URL::asset('produtos/'. '1' . $produto->imagem)}}" 
                                               data-lightbox="{{URL::asset('produtos/'. '1' . $produto->imagem)}}">
                                                <img src="{{URL::asset('produtos/'. $produto->imagem)}}" />
                                            </a></td>
                                        <td id="center">
                                            <a href="{{route('pdv.edit', $produto->id)}}" 
                                               data-toggle="tooltip" 
                                               data-placement="top"
                                               title="Alterar"><i class="fa fa-pencil"></i></a>
                                            &nbsp;<form style="display: inline-block;" method="POST" 
                                                        action="{{route('pdv.destroy', $produto->id)}}"                                                        
                                                        data-toggle="tooltip" data-placement="top"
                                                        title="Excluir" 
                                                        onsubmit="return confirm('Confirma exclusão?')">
                                                {{method_field('DELETE')}}{{ csrf_field() }}                                                
                                                <button type="submit" style="background-color: #fff">
                                                    <a><i class="fa fa-trash-o"></i></a>                                                    
                                                </button></form></td>               
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <img src="{{URL::asset('img/subir.png')}}" 
                 id="up" 
                 style="display: none;" 
                 alt="Ícone Subir ao Topo" 
                 title="Subir ao topo?">
            </body>
            </html>
@stop

resources/views/pdv/pdv.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')

@stop

@section('content')
<!DOCTYPE html>
<html lang="en">

<body>
<div id="line-one">   
            <div class="container">
                <div class="row">
                    <div class="col-md-8" id="center"> 
                        <h1><b>PDV</b></h1>
                        <br>
                    </div>
                </div>
                <div class="box-header">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="#">Panel</a></li>                  
                            <li class="active">Pdv</li>
                        </ol>
                        <br>
                        
                            <div id="pesqClie" class="form form-inline">
                            <form class="form-group" method="post" 
                                  action="{{ route ('search.cliente')}}" > 
                                  {!!csrf_field()!!}                                  
                                  <input type="text" name="cpf" 
                                       class="form-control input-sm pull-left" 
                                       placeholder="CPF do cliente..."
                                       value="{{$cpf}}"
                                       required>
                                       <button class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Adicionar</button>
                            </form> 
                                <button class="btn btn-default btn-sm pull-left" 
                                onClick="window.open('/cliente/exibir','pagename',
                                'resizable,height=600,width=900')" id="color"> 
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                                
                                <input type="text" name="clienteName" size ="40" 
                                       class="form-control input-sm pull-center" 
                                       value="{{$produtos}}"
                                       required>  

                        <div id="pesquisaProduto" class="pull-right">
                            <form class="form-group" method="post" 
                                  action="{{ route ('search.cliente')}}">
                                  {!! csrf_field() !!}   
                                <select name="tipy"  class="form-control input-sm pull-left" required>                                
                                <option value="price1">Consumidor Final</option>
                                <option value="price2">Lojista</option>
                                <option value="price3">Promoção</option>
                                </select>                                  
                                <input type="text" name="CodItem" 
                                       class="form-control input-sm pull-center" 
                                       placeholder="Código do item..." required>                                
                                
                                <input type="text" name="Qtde" size ="5" 
                                       class="form-control input-sm pull-center" 
                                       placeholder="Qtde..." required>                                        
                                <Button class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Adicionar</button>
                            </form>
                            <button class="btn btn-default btn-sm pull-right"   
                            onClick="window.open('/produto','pagename',
                                'resizable,height=600,width=900')"
                                        id="color">                                         
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                        </div>                      
                    </div>  
                           
                </div>
                <div class="row">
                    <div class="col-md-12">   
                        <br /><a href="{{route('truncate')}}" style='background-color:#ff1919' size='35'
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Limpar</a>
                        
                        <a href="{{route('registro')}}" style='background-color: #2dad2d' size='35'
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Registrar</a>
                        <h4 id="center"><b>Registro de Itens </b></h4>
                         
                        <br>
                        
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                    <th id="center">Código</th>
                                        <th>Nome</th>
                                        <th>Descrição</th>
                                        <th id="center">Quantidade</th>
                                        <th>Preço</th>                
                                        <th id="center">Imagem</th>                
                                        <th id="center">Ações</th>              
                                                      
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($produtoPdv as $produto)
                                    <tr>
                                        <td id="center">{{$produto->id}}</td>
                                        <td title="Nome">{{$produto->name}}</td>
                                        <td title="Descrição">{{$produto->description}}</td>
                                        <td title="Quantidade" id="center">{{$produto->quantity}}</td>
                                        <td title="Preço">R$ {{number_format($produto->price, 2,',','.')}}</td> 
                                        <td id="center">
                                            <a href="{{URL::asset('produtos/'. '1' . $produto->imagem)}}" 
                                               data-lightbox="{{URL::asset('produtos/'. '1' . $produto->imagem)}}">
                                                <img src="{{URL::asset('produtos/'. $produto->imagem)}}" />
                                            </a></td>
                                        <td id="center">
                                            <a href="{{route('pdv.edit', $produto->id)}}" 
                                               data-toggle="tooltip" 
                                               data-placement="top"
                                               title="Alterar"><i class="fa fa-pencil"></i></a>
                                            &nbsp;<form style="display: inline-block;" method="POST" 
                                                        action="{{route('pdv.destroy', $produto->id)}}"                                                        
                                                        data-toggle="tooltip" data-placement="top"
                                                        title="Excluir" 
                                                        onsubmit="return confirm('Confirma exclusão?')">
                                                {{method_field('DELETE')}}{{ csrf_field() }}                                                
                                                <button type="submit" style="background-color: #fff">
                                                    <a><i class="fa fa-trash-o"></i></a>                                                    
                                                </button></form></td>               
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <img src="{{URL::asset('img/subir.png')}}" 
                 id="up" 
                 style="display: none;" 
                 alt="Ícone Subir ao Topo" 
                 title="Subir ao topo?">
            </body>
            </html>
@stop