routes/web.php
<?php


$this ->group(['middleware' => ['auth'], 'namespace' => 'produto'], function(){
   $this->get('produto', 'ProdutosController@index');
    
});

Auth::routes();
Route::get('/', function () {
  return view('welcome');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/produto', 'ProdutosController@index')->name('produto');
Route::get('/produto/incluir', 'ProdutosController@create')->name('incluir');
Route::get('/cliente/incluir', 'ClienteController@create')->name('cadastrar');
Route::get('/cliente/exibir', 'ClienteController@index')->name('exibir'); 
Route::resource('product','ProdutosController');
Route::resource('cliente','ClienteController');
Route::resource('pdv','PdvController'); 
Route::resource('OS','OsController');
Route::resource('registro', 'RegistroController');
Route::resource('edit-registro-item', 'EditRegistro');
$this->get('/pdv','PdvController@show')->name('show');
$this->get('/pdv-alter','PdvController@truncate')->name('truncate');
$this->post('/pdv/cliente','PdvController@searchCliente')->name('search.cliente');
Route::get('/registro', 'RegistroController@index')->name('registro');
Route::post('/registro', 'RegistroController@calcular')->name('calcular');
Route::get('/registro-option', 'RegistroController@taxa')->name('registro.taxa');
Route::post('/registro-option', 'RegistroController@destroy')->name('destroy');
Route::post('/registro-register', 'RegistroController@register')->name('register');
Route::post('/OS','OsController@save')->name('OS.save');
Route::get('/OS-show','OsController@show')->name('os.show');
Route::get('/vendas', 'RegistroController@show')->name('vendas');
Route::get('/edit-registro-item', 'RegistroController@alter')->name('alter');
Route::post('/edit-registro', 'RegistroController@remove')->name('remove');
Route::get('/imprimir', 'PdvController@imprimir')->name('imprimir');
Route::get('/imprimir-os', 'OsController@imprimir')->name('imprimir.os');

app/Produto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    protected $fillable = ['name','description','quantity','price1','price2','price3','imagem'];
    protected $guarded = ['id', 'created_at', 'update_at'];
    protected $table = 'produtos';
}

app/Http/Controllers/ProdutosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Produto;

class ProdutosController extends Controller
{
    
    public function index() {
        $produtos = Produto::all();
        $total = Produto::all()->count();
        return view('produto.includeproduto', compact('produtos', 'total'));
    }   

    public function create() {
        return view('produto.include-produto');
    }

    public function store(Request $request) {
        $product = new Produto;
        $product->name = $request->name;
        $product->description = $request->description;
        $product->quantity = $request->quantity;
        $product->price1 = $request->price1;
        $product->price2 = $request->price2;
        $product->price3 = $request->price3;
        $product->imagem = $request->imagem;
        $product->save();
        return redirect()->route('produto')->with('message', 'Produto criado com sucesso!');
    }

    public function show($id) {
        //
    }

    public function edit($id) {
        $product = Produto::findOrFail($id);
        return view('produto.alter-produto', compact('product'));
    }

    public function update(Request $request, $id) {
        $product = Produto::findOrFail($id); 
        $product->name = $request->name;
        $product->description = $request->description;
        $product->quantity = $request->quantity;
        $product->price1 = $request->price1;
        $product->price2 = $request->price2;
        $product->price3 = $request->price3;
        $product->save();
        return redirect()->route('produto')->with('message', 'Produto alterado com sucesso!');
    } 

    public function destroy($id) {
        $product = Produto::findOrFail($id);
        $product->delete();
        return redirect()->route('produto')->with('message', 'Produto excluído com sucesso!');
    }
}

app/Http/Controllers/produto/ProdutosController.php
<?php

namespace App\Http\Controllers\produto;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProdutosController extends Controller
{
    public function index()
    {
        return view('produto.includeproduto');
    }
}

resources/views/produto/alter-produto.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')
<div id="saudacao">
<?php 
  echo "Seja bem vindo(a)!";
?>
</div>
@stop

@section('content')
<!DOCTYPE html>
<html lang="en">
<body>
<div id="line-one">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="center">              
                        <h1><b>Produto</b></h1>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="">Panel</a></li>                  
                            <li><a href="{{route('product.index')}}">Produtos</a></li>                  
                            <li class="active">Alteração</li>
                        </ol>              
                    </div>           
                </div>
                <div class="row">  
                    <br>
                    <h4 id="center"><b>ALTERAÇÃO DOS DADOS DO PRODUTO</b></h4>
                    <br> 
                    <form method="post" 
                          action="{{route('product.update', $product->id)}}" 
                          enctype="multipart/form-data">
                        {!! method_field('put') !!}
                        {{ csrf_field() }}
                        <div class="col-md-6">              
                            <div class="form-group">
                                <label for="name">Nome</label>
                                <input type="text" name="name" 
                                       class="form-control" 
                                       value="{{$product->name or old('name')}}"
                                       required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="foto">Foto</label>
                                <input type="text" 
                                       accept=".gif,.jpg,.png"
                                       class="form-control"
                                       data-toggle="tooltip" 
                                       data-placement="top"
                                       title="Usar arquivo com dimensões 300x300 
                                       - JPG, GIF, PNG"
                                       value="{{$product->imagem or old('imagem')}}">
                            </div>   
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="description">Descrição</label>
                                <input type="text" name="description" 
                                       class="form-control" 
                                       value="{{$product->description or old('description')}}"
                                       required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="quantity">Quantidade</label>
                                <input type="number" name="quantity" 
                                       class="form-control" 
                                       value="{{$product->quantity or old('quantity')}}"
                                       required>
                            </div>    
                        </div>                 
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="price1">Preço Consumidor</label>
                                <input type="text" name="price1"                               
                                       class="form-control"
                                       value="{{$product->price1 or old('price1')}}"
                                       required>
                            </div>
                        </div>          
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="price2">Preço Lojista</label>
                                <input type="text" name="price2"                               
                                       class="form-control"
                                       value="{{$product->price2 or old('price2')}}"
                                       required>
                            </div>
                        </div>   
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="price3">Preço Promocional</label>
                                <input type="text" name="price3"                               
                                       class="form-control"
                                       value="{{$product->price3 or old('price3')}}"
                                       required>
                            </div>
                        </div>                
                        <div class="col-md-12">                   
                            <button type="reset" class="btn btn-default">
                                Limpar
                            </button>
                            <button type="submit" 
                                    class="btn btn-warning" id="black">
                                Alterar
                            </button>
                        </div>
                    </form>             
                </div>
            </div>
        </div>
    </body>
</html>
@stop

resources/views/produto/include-produto.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')
<div id="saudacao">
<?php  
  echo "Seja bem vindo(a)!";
?>
</div>
@stop

@section('content')
<!DOCTYPE html>
<html lang="en">
<body>
<div id="line-one">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="center">              
                        <h1><b>Produto</b></h1>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="">Panel</a></li>                  
                            <li><a href="{{route('product.index')}}">Produtos</a></li>                  
                            <li class="active">Cadastro</li>
                        </ol>              
                    </div>          
                </div>
                <div class="row">  
                    <br>
                    <h4 id="center"><b>CADASTRO DE PRODUTO</b></h4>
                    <br> 
                    <form method="post" 
                          action="{{route('product.store')}}" 
                          enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="col-md-6">               
                            <div class="form-group">
                                <label for="name">Nome</label>
                                <input type="text" name="name" 
                                       class="form-control" 
                                       required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="foto"> Foto </label>
                                <input type="text" name="imagem"
                                       accept=".gif,.jpg,.png"
                                       class="form-control"
                                       data-toggle="tooltip" 
                                       data-placement="top"
                                       title="Usar arquivo com dimensões 300x300 
                                       - JPG, GIF, PNG">
                            </div>   
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="description">Descrição</label>
                                <input type="text" name="description" 
                                       class="form-control" 
                                       required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="quantity">Quantidade</label>
                                <input type="number" name="quantity" 
                                       class="form-control" 
                                       required>
                            </div>    
                        </div>                 
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="price1"> Preço Consumidor </label>
                                <input type="text" name="price1"                               
                                       class="form-control">
                            </div>
                        </div>       
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="price2"> Preço Lojista</label>
                                <input type="text" name="price2"                               
                                       class="form-control">
                            </div>
                        </div>  
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="price3"> Preço Promocional</label>
                                <input type="text" name="price3"                               
                                       class="form-control">
                            </div>
                        </div>                  
                        <div class="col-md-12">                   
                            <button type="reset" class="btn btn-default">
                                Limpar
                            </button>
                            <button type="submit" 
                                    class="btn btn-warning" id="black">
                                Cadastrar
                            </button>
                        </div>
                    </form>             
                </div>
            </div>
        </div>
    </body>
</html>
@stop

resources/views/produto/includeproduto.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')
<div id="saudacao">
<?php 
  echo "Seja bem vindo(a)!";
?>
</div>
@stop

@section('content')
<!DOCTYPE html>
<html lang="en">
<body>
<div id="line-one">   
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="center"> 
                        <h1><b>Produtos</b></h1>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="#">Panel</a></li>                  
                            <li class="active">Produtos</li>
                        </ol>
                        <br>
                        <a href="{{route('product.create')}}" 
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Adicionar</a>
                        <a href="" 
                           class="btn btn-default btn-sm pull-right">
                            <i class="fa fa-book"></i> Relatório</a>
                        <div id="pesquisa" class="pull-right">
                            <form class="form-group" method="post" 
                                  action="">                                   
                                <input type="text" name="pesquisar" 
                                       class="form-control input-sm pull-left" 
                                       placeholder="Pesquisar por nome..." required> 
                                <button class="btn btn-default btn-sm pull-right" 
                                        id="color"> 
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </form>
                        </div>
                    </div>           
                </div>
                <div class="row">
                    <div class="col-md-12">   
                        <br />
                        <h4 id="center"><b>PRODUTOS CADASTRADOS ({{$total}})</b></h4>
                        <br>
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th id="center">Código</th>
                                        <th>Nome</th>
                                        <th>Descrição</th>
                                        <th id="center">Quantidade</th>
                                        <th>Preço Consumidor</th>         
                                        <th>Preço Lojista</th>           
                                        <th id="center">Imagem</th>                
                                        <th id="center">Ações</th>                
                                    </tr>
                                </thead> 
                                <tbody>
                                    @foreach($produtos as $produto)
                                    <tr>
                                        <td id="center">{{$produto->id}}</td>
                                        <td title="Nome">{{$produto->name}}</td>
                                        <td title="Descrição">{{$produto->description}}</td>
                                        <td title="Quantidade" id="center">{{$produto->quantity}}</td>
                                        <td title="Preço">R$ {{number_format($produto->price1, 2,',','.')}}</td> 
                                        <td title="Preço">R$ {{number_format($produto->price2, 2,',','.')}}</td> 
                                        <td id="center">
                                            <a href="{{URL::asset('produtos/'. '1' . $produto->imagem)}}" 
                                               data-lightbox="{{URL::asset('produtos/'. '1' . $produto->imagem)}}">
                                                <img src="{{URL::asset('produtos/'. $produto->imagem)}}" />
                                            </a></td>
                                        <td id="center">
                                            <a href="{{route('product.edit', $produto->id)}}" 
                                               data-toggle="tooltip" 
                                               data-placement="top"
                                               title="Alterar"><i class="fa fa-pencil"></i></a>
                                            &nbsp;<form style="display: inline-block;" method="POST" 
                                                        action="{{route('product.destroy', $produto->id)}}"                                                        
                                                        data-toggle="tooltip" data-placement="top"
                                                        title="Excluir" 
                                                        onsubmit="return confirm('Confirma exclusão?')">
                                                {{method_field('DELETE')}}{{ csrf_field() }}                                                
                                                <button type="submit" style="background-color: #fff">
                                                    <a><i class="fa fa-trash-o"></i></a>                                                    
                                                </button></form></td>               
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <img src="{{URL::asset('img/subir.png')}}" 
                 id="up" 
                 style="display: none;" 
                 alt="Ícone Subir ao Topo" 
                 title="Subir ao topo?">
            </body>
            </html>
@stop