routes/web.php
<?php


$this ->group(['middleware' => ['auth'], 'namespace' => 'produto'], function(){
   $this->get('produto', 'ProdutosController@index');
    
});

Auth::routes();
Route::get('/', function () {
  return view('welcome');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/produto', 'ProdutosController@index')->name('produto');
Route::get('/produto/incluir', 'ProdutosController@create')->name('incluir');
Route::get('/cliente/incluir', 'ClienteController@create')->name('cadastrar');
Route::get('/cliente/exibir', 'ClienteController@index')->name('exibir'); 
Route::resource('product','ProdutosController');
Route::resource('cliente','ClienteController');
Route::resource('pdv','PdvController'); 
Route::resource('OS','OsController');
Route::resource('registro', 'RegistroController');
Route::resource('edit-registro-item', 'EditRegistro');
$this->get('/pdv','PdvController@show')->name('show');
$this->get('/pdv-alter','PdvController@truncate')->name('truncate');
$this->post('/pdv/cliente','PdvController@searchCliente')->name('search.cliente');
Route::get('/registro', 'RegistroController@index')->name('registro');
Route::post('/registro', 'RegistroController@calcular')->name('calcular');
Route::get('/registro-option', 'RegistroController@taxa')->name('registro.taxa');
Route::post('/registro-option', 'RegistroController@destroy')->name('destroy');
Route::post('/registro-register', 'RegistroController@register')->name('register');
Route::post('/OS','OsController@save')->name('OS.save');
Route::get('/OS-show','OsController@show')->name('os.show');
Route::get('/vendas', 'RegistroController@show')->name('vendas');
Route::get('/edit-registro-item', 'RegistroController@alter')->name('alter');
Route::post('/edit-registro', 'RegistroController@remove')->name('remove');
Route::get('/imprimir', 'PdvController@imprimir')->name('imprimir');
Route::get('/imprimir-os', 'OsController@imprimir')->name('imprimir.os');

app/Registro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Registro extends Model
{
    protected $fillable = ['cliente','valor_pedido','taxa','dinheiro','credito','debito','boleto','troco'];
    protected $guarded = ['id', 'created_at', 'update_at'];
    protected $table = 'registros'; 
}

app/Http/Controllers/RegistroController.php
<?php

namespace App\Http\Controllers;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\Printer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Pdv;
use App\taxa;
use App\Registro_pdv;
use App\Registro;
use App\pagamento;
use App\registro_edit;

class RegistroController extends Controller
{
    public function index(Request $request) {
        $reg = Pdv::all();
        
        $subtotal = DB::table('pdvs')->select('price');
        $total = $subtotal->sum('price');                
        $taxa = DB::table('taxas')->select('taxa')->orderBy('id', 'desc')->first()->taxa;
        $stotal = $total + $taxa;        
        $dinheiro = $request->input('dinheiro');
        $credito = $request->input('credito');
        $debito = $request->input('debito');
        $boleto = $request->input('boleto');
        $totalp = $request->input('troco');
        $soma = ($dinheiro + $credito + $debito + $boleto);
        if(empty($soma)){
            $troco = "0.00";
            $falta = $stotal;
        }else{
        $troco = ($stotal - $soma) *(-1);
        $falta = ($stotal - $soma);
        }
        

        return view('pdv.pdv-registro', 
        compact('total', 'stotal', 'taxa', 'dinheiro','credito','debito','boleto','troco', 'falta'));
    }  
    public function calcular(Request $request) {
        $subtotal = DB::table('pdvs')->select('price');
        $total = $subtotal->sum('price');                
        $taxa = DB::table('taxas')->select('taxa')->orderBy('id', 'desc')->first()->taxa;
        $stotal = $total + $taxa;  
        $dinheiro = $request->input('dinheiro');
        $credito = $request->input('credito');
        $debito = $request->input('debito');
        $boleto = $request->input('boleto');
        $totalp = $request->input('troco');
        $soma = ($dinheiro + $credito + $debito + $boleto);
        if(empty($soma)){
            $troco = "0.00";
            
        }else{
        $troco = ($stotal - $soma) *(-1);
        $falta = ($stotal - $soma);
        }
        $product = new pagamento;
        $product->dinheiro = $dinheiro;
        $product->credito = $credito;
        $product->debito = $debito;
        $product->boleto = $boleto;
        $product->troco = $troco;
        //dd($dinheiro,$credito,$debito,$boleto);
        $product->save();
        return redirect()->route('registro', compact('total', 'stotal', 'taxa',
         'dinheiro','credito','debito','boleto','troco', 'falta'));
    }
    public function taxa(Request $request) {
        
        $product = new taxa;
        $product->taxa = $request->taxa; 
        $product->save();
        return redirect()->route('registro')->with('message', 'Produto criado com sucesso!');
 
    }
    public function destroy($id) {
        $product = Registro::findOrFail($id);
        $product->delete(); 
        return redirect()->route('vendas')->with('message', 'Produto criado com sucesso!');
 }

    public function register(Request $request){
        setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
        date_default_timezone_set('America/Sao_Paulo');
        $data = strftime('%d de %B de %Y', strtotime('today'));
        $today = date("H:i:s");          
        $id = Registro::all()->count();
        $venda = $id + 1;
        $cliente = DB::table('pdvs')->select('cliente')->value('cliente');        
        $telefone = DB::table('cliente_tables')->where('name',$cliente)->value('celular');
        $cep = DB::table('cliente_tables')->where('name',$cliente)->value('cep');
        $rua = DB::table('cliente_tables')->where('name',$cliente)->value('rua');
        $bairro = DB::table('cliente_tables')->where('name',$cliente)->value('Bairro');
        $cidade = DB::table('cliente_tables')->where('name',$cliente)->value('Cidade');
        $user = auth()->user()->name;
        $subtotal = DB::table('pdvs')->select('price');
        $total = $subtotal->sum('price');                
        $taxa = DB::table('taxas')->select('taxa')->orderBy('id', 'desc')->first()->taxa;
        $stotal = $total + $taxa;        
        $dinheiro = DB::table('pagamentos')->select('dinheiro')->orderBy('id', 'desc')->first()->dinheiro;
        $credito = DB::table('pagamentos')->select('credito')->orderBy('id', 'desc')->first()->credito;
        $debito = DB::table('pagamentos')->select('debito')->orderBy('id', 'desc')->first()->debito;
        $boleto = DB::table('pagamentos')->select('boleto')->orderBy('id', 'desc')->first()->boleto;
        $troco = DB::table('pagamentos')->select('troco')->orderBy('id', 'desc')->first()->troco;
        $product = new registro;
        $product->cliente = $cliente;
        $product->valor_pedido = $total;
        $product->taxa = $taxa;
        $product->dinheiro = $dinheiro;
        $product->credito = $credito;
        $product->debito = $debito;
        $product->boleto = $boleto;
        $product->troco = $troco;
        $product->save();
        $inserts = [];
        $bids = DB::table('pdvs')->select('id','cliente','name','description','quantity','price','imagem','created_at')->get();
        foreach($bids as $bid) {
        $inserts[] = [ 'id'  => $bid->id,
        'cliente'  => $bid->cliente,
        'name'  => $bid->name,
        'description'  => $bid->description,
        'quantity'  => $bid->quantity,
        'price'  => $bid->price,
        'imagem'  => $bid->imagem,
        'created_at' => $date = date('Y-m-d H:i:s'),
        
    ]; 
    
        }
    try {
        // Enter the share name for your USB printer here
        //$connector = null;
        $connector = new WindowsPrintConnector("Receipt Printer");
        /*Print a "Hello world" receipt" */
        $printer = new Printer($connector);
        $printer -> text("JR INFORCELL DISTRIBUIDORA\n");
        $printer -> text("00.000.000/0001-91\n");
        $printer -> text("------------------------------------------------\n");
        $printer -> text("COMPROVANTE DE REGISTRO DE\n");
        $printer -> text("NOTA FISCAL DE VENDA AO CONSUMIDOR\n");
        $printer -> text("------------------------------------------------\n");
        $printer -> text("Cliente:     {$cliente}\n");
        $printer -> text("Endereço:    {$rua}\n");
        $printer -> text("Bairro:      {$bairro}\n");
        $printer -> text("Cidade:      {$cidade}\n");
        $printer -> text("CEP:         {$cep}\n");
        $printer -> text("Telefone:    {$telefone}\n");        
        $printer -> text("------------------------------------------------\n");
        $printer -> text("Venda:  Nº {$venda}   {$today}    {$data}\n");
        $printer -> text("------------------------------------------------\n");
        $printer -> text("Produtos\n");
        $printer -> text("------------------------------------------------\n");
        $printer -> text("Nome               Qtde  Valor Uni(R$) Total(R$)\n");
        $printer -> text("------------------------------------------------\n");  
        //dd($inserts2);
        $bids2 = DB::table('pdvs')->select('name','description','quantity','price','priceone')->get();
    
        foreach($bids2 as $bid2 ) {
        $inserts2[] = [ 
        'name'  => $bid2->name,
        'description'  => $bid2->description,
        'quantity'  => $bid2->quantity,
        'price'  => $bid2->price,
        'priceone'  => $bid2->priceone,
        ]; 
        $printer ->text($bid2->name."    ".$bid2->quantity."     ".$bid2->priceone."     ".$bid2->price."\n");
        }
        $printer -> text("------------------------------------------------\n");
        $printer -> text("Total:                               R$ {$total}\n");
        $printer -> text("Taxa:                                R$ {$taxa}\n");
        $printer -> text("Troco:                               R$ {$troco}\n");
        $printer -> text("------------------------------------------------\n");
        $printer -> text("Observação: NSU: 8883 11/05/2018 12:29:54\n");
        $printer -> text("Não trocamos peças danificadas, Flex rasgado, películas removidas ou selos de garantia danificados. Favor testar as peças antes de montar os aparelhos.\n");
        $printer -> text("------------------------------------------------\n");
        $printer -> text("                    Atendente:   {$user} \n");
        $printer -> cut();
        
       // Close printer 
        $printer -> close();
    } catch (Exception $e) {
        echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
    }
        DB::table('registro_pdvs')->insert($inserts);
        DB::table('pdvs')->truncate();
        DB::table('cliente_locals')->truncate();
        return redirect()->route('show')->with('message', 'Produto criado com sucesso!');
    }
    public function show() {
        $produtos = registro::all();
        $total = registro::all()->count();        
        DB::table('registro_edits')->truncate(); 
        return view('registro.show-pdv', compact('produtos', 'total'));
    }  

    public function edit($id) {
        $list = DB::table('registros')->where('id',$id)->value('created_at');
        $produtos = DB::table('registro_pdvs')->where('created_at', $list)->get();
        $cliente = DB::table('registros')->where('id',$id)->value('cliente'); 
        $cpf = DB::table('cliente_tables')->where('name',$cliente)->value('cpf'); 
        $bids = DB::table('registro_pdvs')->where('created_at', $list)
        ->select('id','cliente','name','description','quantity','price','imagem','created_at')->get();
        
        foreach($bids as $bid) {
            $inserts[] = [ 
            'id'  => $bid->id,
            'cpf' => $cpf,
            'cliente'  => $bid->cliente,
            'name'  => $bid->name,
            'description'  => $bid->description,
            'quantity'  => $bid->quantity, 
            'price'  => $bid->price,
            'imagem'  => $bid->imagem,

resources/views/Registro/edit-registro-item.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')

@stop

@section('content')
<!DOCTYPE html>
<html lang="en">

<body>
<div id="line-one">   
            <div class="container">
                <div class="row">
                    <div class="col-md-8" id="center"> 
                        <h1><b>Editar Venda</b></h1>
                        <br>
                    </div>
                </div>
                <div class="box-header">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="#">Panel</a></li>                  
                            <li class="active">Editar Venda</li>
                        </ol>
                        <br>
                        
                            <div id="pesqClie" class="form form-inline">
                            <form class="form-group" method="post" 
                                  action="{{ route ('search.cliente')}}" > 
                                  {!!csrf_field()!!}                                  
                                  <input type="text" name="cpf" 
                                       class="form-control input-sm pull-left" 
                                       placeholder="CPF do cliente..."
                                       value="{{$cpf}}"
                                       required>
                                <button class="btn btn-default btn-sm pull-right" 
                                        id="color"> 
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                                </form> 
                                <input type="text" name="clienteName" size ="70" 
                                       class="form-control input-sm pull-center" 
                                       value="{{$cliente}}"
                                       required>  

                        <div id="pesquisaProduto" class="pull-right">
                            <form class="form-group" method="post" 
                                  action="{{ route ('search.cliente')}}">
                                  {!! csrf_field() !!}                                   
                                <input type="text" name="CodItem" 
                                       class="form-control input-sm pull-left" 
                                       placeholder="Código do item..." required> 
                                <button class="btn btn-default btn-sm pull-right" 
                                        id="color">                                         
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                                <input type="text" name="Qtde" size ="5" 
                                       class="form-control input-sm pull-center" 
                                       placeholder="Qtde..." required>                                        
                                <a href="{{route('product.create')}}" 
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Adicionar</a>
                            </form>
                        </div>                      
                    </div>  
                           
                </div>
                <div class="row">
                    <div class="col-md-12">   
                        <br /><a href="{{route('truncate')}}" style='background-color:#ff1919' size='35'
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Limpar</a>
                        
                        <a href="{{route('registro')}}" style='background-color: #2dad2d' size='35'
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Registrar</a>
                        <h4 id="center"><b>Registro de Itens </b></h4>
                         
                        <br>
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                    <th id="center">Código</th>
                                        <th>Nome</th>
                                        <th>Descrição</th>
                                        <th id="center">Quantidade</th>
                                        <th>Preço</th>                
                                        <th id="center">Imagem</th>                
                                        <th id="center">Ações</th>              
                                                      
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($produtos as $produto)
                                    <tr>
                                        <td id="center">{{$produto->id}}</td>
                                        <td title="Nome">{{$produto->name}}</td>
                                        <td title="Descrição">{{$produto->description}}</td>
                                        <td title="Quantidade" id="center">{{$produto->quantity}}</td>
                                        <td title="Preço">R$ {{number_format($produto->price, 2,',','.')}}</td> 
                                        <td id="center">
                                            <a href="{{URL::asset('produtos/'. '1' . $produto->imagem)}}" 
                                               data-lightbox="{{URL::asset('produtos/'. '1' . $produto->imagem)}}">
                                                <img src="{{URL::asset('produtos/'. $produto->imagem)}}" />
                                            </a></td>
                                        <td id="center">
                                            <a href="{{route('edit-registro-item.edit', $produto->id)}}" 
                                               data-toggle="tooltip" 
                                               data-placement="top"
                                               title="Alterar"><i class="fa fa-pencil"></i></a>
                                            &nbsp;<form style="display: inline-block;" method="POST" 
                                                        action="{{route('edit-registro-item.destroy', $produto->id)}}"                                                        
                                                        data-toggle="tooltip" data-placement="top"
                                                        title="Excluir" 
                                                        onsubmit="return confirm('Confirma exclusão?')">
                                                {{method_field('DELETE')}}{{ csrf_field() }}                                                
                                                <button type="submit" style="background-color: #fff">
                                                    <a><i class="fa fa-trash-o"></i></a>                                                    
                                                </button></form></td>               
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <img src="{{URL::asset('img/subir.png')}}" 
                 id="up" 
                 style="display: none;" 
                 alt="Ícone Subir ao Topo" 
                 title="Subir ao topo?">
            </body>
            </html>
@stop

resources/views/Registro/edit-registro.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')

@stop

@section('content')
<!DOCTYPE html>
<html lang="en">

<body>
<div id="line-one">   
            <div class="container">
                <div class="row">
                    <div class="col-md-8" id="center"> 
                        <h1><b>Editar Venda</b></h1>
                        <br>
                    </div>
                </div>
                <div class="box-header">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="#">Panel</a></li>                  
                            <li class="active">Editar Venda</li>
                        </ol>
                        <br>
                        
                            <div id="pesqClie" class="form form-inline">
                            <form class="form-group" method="post" 
                                  action="{{ route ('search.cliente')}}" > 
                                  {!!csrf_field()!!}                                  
                                  <input type="text" name="cpf" 
                                       class="form-control input-sm pull-left" 
                                       placeholder="CPF do cliente..."
                                       value="{{$cpf}}"
                                       required>
                                <button class="btn btn-default btn-sm pull-right" 
                                        id="color"> 
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                                </form> 
                                <input type="text" name="clienteName" size ="70" 
                                       class="form-control input-sm pull-center" 
                                       value="{{$cliente}}"
                                       required>  

                        <div id="pesquisaProduto" class="pull-right">
                            <form class="form-group" method="post" 
                                  action="{{ route ('search.cliente')}}">
                                  {!! csrf_field() !!}                                   
                                <input type="text" name="CodItem" 
                                       class="form-control input-sm pull-left" 
                                       placeholder="Código do item..." required> 
                                <button class="btn btn-default btn-sm pull-right" 
                                        id="color">                                         
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                                <input type="text" name="Qtde" size ="5" 
                                       class="form-control input-sm pull-center" 
                                       placeholder="Qtde..." required>                                        
                                <a href="{{route('product.create')}}" 
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Adicionar</a>
                            </form>
                        </div>                      
                    </div>  
                           
                </div>
                <div class="row">
                    <div class="col-md-12">   
                        <br /><a href="{{route('truncate')}}" style='background-color:#ff1919' size='35'
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Limpar</a>
                        
                        <a href="{{route('registro')}}" style='background-color: #2dad2d' size='35'
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Registrar</a>
                        <h4 id="center"><b>Registro de Itens </b></h4>
                         
                        <br>
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                    <th id="center">Código</th>
                                        <th>Nome</th>
                                        <th>Descrição</th>
                                        <th id="center">Quantidade</th>
                                        <th>Preço</th>                
                                        <th id="center">Imagem</th>                
                                        <th id="center">Ações</th>              
                                                      
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($produtos as $produto)
                                    <tr>
                                        <td id="center">{{$produto->id}}</td>
                                        <td title="Nome">{{$produto->name}}</td>
                                        <td title="Descrição">{{$produto->description}}</td>
                                        <td title="Quantidade" id="center">{{$produto->quantity}}</td>
                                        <td title="Preço">R$ {{number_format($produto->price, 2,',','.')}}</td> 
                                        <td id="center">
                                            <a href="{{URL::asset('produtos/'. '1' . $produto->imagem)}}" 
                                               data-lightbox="{{URL::asset('produtos/'. '1' . $produto->imagem)}}">
                                                <img src="{{URL::asset('produtos/'. $produto->imagem)}}" />
                                            </a></td>
                                        <td id="center">
                                            <a href="{{route('alter')}}" 
                                               data-toggle="tooltip" 
                                               data-placement="top"
                                               title="Alterar"><i class="fa fa-pencil"></i></a>
                                            &nbsp;<form style="display: inline-block;" method="POST" 
                                                        action="{{route('pdv.destroy', $produto->id)}}"                                                        
                                                        data-toggle="tooltip" data-placement="top"
                                                        title="Excluir" 
                                                        onsubmit="return confirm('Confirma exclusão?')">
                                                {{method_field('DELETE')}}{{ csrf_field() }}                                                
                                                <button type="submit" style="background-color: #fff">
                                                    <a><i class="fa fa-trash-o"></i></a>                                                    
                                                </button></form></td>               
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <img src="{{URL::asset('img/subir.png')}}" 
                 id="up" 
                 style="display: none;" 
                 alt="Ícone Subir ao Topo" 
                 title="Subir ao topo?">
            </body>
            </html>
@stop