routes/web.php
<?php


$this ->group(['middleware' => ['auth'], 'namespace' => 'produto'], function(){
   $this->get('produto', 'ProdutosController@index');
    
});

Auth::routes();
Route::get('/', function () {
  return view('welcome');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/produto', 'ProdutosController@index')->name('produto');
Route::get('/produto/incluir', 'ProdutosController@create')->name('incluir');
Route::get('/cliente/incluir', 'ClienteController@create')->name('cadastrar');
Route::get('/cliente/exibir', 'ClienteController@index')->name('exibir'); 
Route::resource('product','ProdutosController');
Route::resource('cliente','ClienteController');
Route::resource('pdv','PdvController'); 
Route::resource('OS','OsController');
Route::resource('registro', 'RegistroController');
Route::resource('edit-registro-item', 'EditRegistro');
$this->get('/pdv','PdvController@show')->name('show');
$this->get('/pdv-alter','PdvController@truncate')->name('truncate');
$this->post('/pdv/cliente','PdvController@searchCliente')->name('search.cliente');
Route::get('/registro', 'RegistroController@index')->name('registro');
Route::post('/registro', 'RegistroController@calcular')->name('calcular');
Route::get('/registro-option', 'RegistroController@taxa')->name('registro.taxa');
Route::post('/registro-option', 'RegistroController@destroy')->name('destroy');
Route::post('/registro-register', 'RegistroController@register')->name('register');
Route::post('/OS','OsController@save')->name('OS.save');
Route::get('/OS-show','OsController@show')->name('os.show');
Route::get('/vendas', 'RegistroController@show')->name('vendas');
Route::get('/edit-registro-item', 'RegistroController@alter')->name('alter');
Route::post('/edit-registro', 'RegistroController@remove')->name('remove');
Route::get('/imprimir', 'PdvController@imprimir')->name('imprimir');
Route::get('/imprimir-os', 'OsController@imprimir')->name('imprimir.os');

app/ClienteTable.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ClienteTable extends Model
{
    protected $fillable = ['name','cpf','email','celular','cep','rua','bairro','cidade'];
    protected $guarded = ['id', 'created_at', 'update_at'];
    protected $table = 'cliente_tables';
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ClienteTable;

class ClienteController extends Controller
{
    public function index() {
        $produtos = ClienteTable::all();
        $total = ClienteTable::all()->count();        
        return view('cliente.show-cliente', compact('produtos', 'total'));
    }  

    public function create() {
        return view('cliente.include-cliente');
    }

    public function store(Request $request) {
        $product = new ClienteTable;
        $product->name = $request->name;
        $product->cpf = $request->cpf;
        $product->email = $request->email;
        $product->celular = $request->celular;
        $product->cep = $request->cep;
        $product->rua = $request->rua;
        $product->bairro = $request->bairro;
        $product->cidade = $request->cidade;
        $product->save();
        return redirect()->route('exibir')->with('message', 'Cliente cadastrado com sucesso!');
    } 

    public function show($id) {
        $produto = ClienteTable::findOrFail($id);
        
        return view('pdv.pdv', compact('produto'));   
    }

    public function edit($id) {
        $product = ClienteTable::findOrFail($id);
        return view('cliente.alter-cliente', compact('product'));
    }

    public function update(Request $request, $id) {
        $product = ClienteTable::findOrFail($id); 
        $product->name = $request->name;
        $product->cpf = $request->cpf;
        $product->email = $request->email;
        $product->celular = $request->celular;
        $product->cep = $request->cep;
        $product->rua = $request->rua;
        $product->bairro = $request->bairro;
        $product->cidade = $request->cidade;
        $product->save();
        return redirect()->route('exibir')->with('message', 'Cliente alterado com sucesso!');
    } 

    public function destroy($id) {
        $product = ClienteTable::findOrFail($id);
        $product->delete();
        return redirect()->route('exibir')->with('message', 'Produto excluído com sucesso!');
    }

}

resources/views/cliente/Alter-cliente.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')
<div id="saudacao">
<?php 
  echo "Seja bem vindo(a)!";
?>
</div>
@stop

@section('content')
<!DOCTYPE html>
<html lang="en">
<body>
<div id="line-one">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="center">              
                        <h1><b>Clientes</b></h1>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="">Panel</a></li>                  
                            <li><a href="{{route('exibir')}}">Cliente</a></li>                  
                            <li class="active">Alteração</li>
                        </ol>              
                    </div>          
                </div>
                <div class="row">  
                    <br>
                    <h4 id="center"><b>ALTERAÇÃO DOS DADOS DO CLIENTE</b></h4>
                    <br> 
                    <form method="post" 
                          action="{{route('cliente.update', $product->id)}}" 
                          enctype="multipart/form-data">
                        {!! method_field('put') !!}
                        {{ csrf_field() }}
                        <div class="col-md-6">              
                            <div class="form-group">
                                <label for="name">Nome</label>
                                <input type="text" name="name" 
                                       class="form-control" 
                                       value="{{$product->name or old('name')}}"
                                       required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="Email">Email</label>
                                <input type="text" name="email"                                        
                                       class="form-control"                                       
                                       value="{{$product->email or old('email')}}">
                            </div>   
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="celular">Celular</label>
                                <input type="text" name="celular" 
                                       class="form-control" 
                                       value="{{$product->celular or old('celular')}}"
                                       required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="CPF">CPF</label>
                                <input type="text" name="cpf" 
                                       class="form-control" 
                                       value="{{$product->cpf or old('cpf')}}"
                                       required>
                            </div>    
                        </div>                 
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="cep">CEP</label>
                                <input type="text" name="cep"                               
                                       class="form-control"
                                       value="{{$product->cep or old('cep')}}"
                                       required>
                            </div>
                        </div>      
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="rua"> Rua/Nº </label>
                                <input type="text" name="rua"                                 
                                       class="form-control"
                                       value="{{$product->rua or old('rua')}}"
                                       required>
                            </div>
                        </div>   
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="bairro"> Bairro </label>
                                <input type="text" name="bairro"                              
                                       class="form-control"
                                       value="{{$product->bairro or old('bairro')}}"
                                       required>
                            </div> 
                        </div>           
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="cidade"> Cidade/UF </label>
                                <input type="text" name="cidade"                              
                                       class="form-control"
                                       value="{{$product->cidade or old('cidade')}}"
                                       required>
                            </div>
                        </div>          
                        <div class="col-md-12">                   
                            <button type="reset" class="btn btn-default">
                                Limpar
                            </button>
                            <button type="submit" 
                                    class="btn btn-warning" id="black">
                                Alterar
                            </button>
                        </div>
                    </form>             
                </div>
            </div>
        </div>
    </body>
</html>
@stop

resources/views/cliente/include-cliente.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')
<div id="saudacao">
<?php 
  echo "Seja bem vindo(a)!";
?>
</div>
@stop

@section('content')
<!DOCTYPE html>
<html lang="en">
<body>
<div id="line-one">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="center">              
                        <h1><b>Clientes</b></h1>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="">Panel</a></li>                  
                            <li><a href="{{route('cliente.store')}}">Clientes</a></li>                  
                            <li class="active">Cadastro</li>
                        </ol>              
                    </div>          
                </div>
                <div class="row">  
                    <br>
                    <h4 id="center"><b>CADASTRO DE CLIENTES</b></h4>
                    <br> 
                    <form method="post" 
                          action="{{route('cliente.store')}}" 
                          enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="col-md-6">              
                            <div class="form-group">
                                <label for="name">Nome</label>
                                <input type="text" name="name" 
                                       class="form-control" 
                                       required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="Email">Email</label>
                                <input type="text" name="email"                               
                                       class="form-control">
                            </div> 
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="celular">Celular</label>
                                <input type="text" name="celular"                               
                                       class="form-control">
                            </div> 
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="CPF">CPF</label>
                                <input type="text" name="cpf" 
                                       class="form-control" 
                                       required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="Cep">CEP</label>
                                <input type="text" name="cep" 
                                       class="form-control" 
                                       required>
                            </div>    
                        </div>                                                    
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="rua"> Rua/Nº </label>
                                <input type="text" name="rua"                               
                                       class="form-control">
                            </div>
                        </div>          
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="bairro"> Bairro </label>
                                <input type="text" name="bairro"                               
                                       class="form-control">
                            </div>  
                        </div>   
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="cidade"> Cidade/UF </label>
                                <input type="text" name="cidade"                               
                                       class="form-control">
                            </div>  
                        </div>       
                        <div class="col-md-12">                   
                            <button type="reset" class="btn btn-default">
                                Limpar
                            </button>
                            <button type="submit" 
                                    class="btn btn-warning" id="black">
                                Cadastrar
                            </button>
                        </div>
                    </form>             
                </div>
            </div>
        </div>
    </body>
</html>
@stop

resources/views/cliente/show-cliente.blade.php
@extends('adminlte::page')

@section('title', 'JR InforCell')

@section('content_header')
<div id="saudacao">
<?php 
  echo "Seja bem vindo(a)!";
?>
</div>
@stop

@section('content')
<!DOCTYPE html>
<html lang="en">
<body>
<div id="line-one">    
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="center"> 
                        <h1><b>Clientes</b></h1>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="#">Panel</a></li>                  
                            <li class="active">Clientes</li>
                        </ol>
                        <br>
                        <a href="{{route('cadastrar')}}" 
                           class="btn btn-default btn-sm pull-right">
                            <span class="glyphicon glyphicon-plus"></span> Adicionar</a>
                        <a href="" 
                           class="btn btn-default btn-sm pull-right">
                            <i class="fa fa-book"></i> Relatório</a>
                        <div id="pesquisa" class="pull-right">
                            <form class="form-group" method="post" 
                                  action="#">                                   
                                <input type="text" name="pesquisar" 
                                       class="form-control input-sm pull-left" 
                                       placeholder="Pesquisar por nome..." required> 
                                <button class="btn btn-default btn-sm pull-right" 
                                        id="color"> 
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </form>
                        </div>                        
                    </div>           
                </div>
                <div class="row">
                    <div class="col-md-12">   
                        <br />
                        <h4 id="center"><b>CLIENTES CADASTRADOS ({{$total}})</b></h4>
                        <br>
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th id="center">Código</th>
                                        <th>Nome</th>
                                        <th>CPF</th>
                                        <th id="center">Email</th>
                                        <th>Celular</th>                
                                        <th id="center">Rua</th>                
                                        <th>Bairro</th>    
                                        <th>Status</th>               
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($produtos as $produto)
                                    <tr>
                                        <td id="center">{{$produto->id}}</td>
                                        <td title="Nome">{{$produto->name}}</td>
                                        <td title="CPF">{{$produto->cpf}}</td>
                                        <td title="Email" id="center">{{$produto->email}}</td>
                                        <td title="Celular"> {{($produto->celular)}}</td> 
                                        <td title="Rua"> {{($produto->rua)}}</td>      
                                        <td title="Bairro"> {{($produto->Bairro)}}</td>                                                                           
                                        <td id="center">
                                            <a href="{{route('cliente.edit', $produto->id)}}" 
                                               data-toggle="tooltip" 
                                               data-placement="top"
                                               title="Alterar"><i class="fa fa-pencil"></i></a>
                                            &nbsp;<form style="display: inline-block;" method="POST" 
                                                        action="{{route('cliente.destroy', $produto->id)}}"                                                        
                                                        data-toggle="tooltip" data-placement="top"
                                                        title="Excluir" 
                                                        onsubmit="return confirm('Confirma exclusão?')">
                                                {{method_field('DELETE')}}{{ csrf_field() }}                                                
                                                <button type="submit" style="background-color: #fff">
                                                    <a><i class="fa fa-trash-o"></i></a>                                                    
                                                </button></form></td>               
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <img src="{{URL::asset('img/subir.png')}}" 
                 id="up" 
                 style="display: none;" 
                 alt="Ícone Subir ao Topo" 
                 title="Subir ao topo?">
            </body>
            </html>
@stop